### PR TITLE
support building a single test executable for all machines

### LINKED ISSUE #30: Running directly from `cargo test`
Hello,

First, once again thank you for netsim-embed! I'm trying to upgrade to 0.7, and am hitting an issue I can't figure out.

AFAICT, `NetworkBuilder` was renamed to `Netsim`. I was using it in ways similar to this:
```rust
    futures::executor::block_on(async move {
        let mut net = Netsim::<String, String>::new(Ipv4Range::local_subnet_10());

        let last_recipient = net.spawn_machine(|_, mut evt| async move {
            // ... spawn a machine that's ready to receive emails and triggers evt once the email was received
        });

        let kannader_server = net.spawn_machine(move |_, _| async move {
            // spawn a machine that's ready to forward emails
            kannader::run(&opt, shutdown).expect("Failed to run kannader");
        });

        let _initial_client = net.spawn_machine(move |_, _| async move {
            // ... spawn a machine that sends an email
        });

        net.spawn().machine(0).recv().await.unwrap();
    });
```

However, with 0.7, it seems to me like we can only spawn `Command`s any longer with `spawn_machine`, and no longer direct closures.

Do you know where I should look at in order to recover behavior similar to the previous `spawn_machine`?

### PR DESCRIPTION
**Pull request by Ekleog**
Fixes #30

BTW, I couldn't figure out what the C and E parameters to Netsim are used for. It seems to me like they're not to be used any longer as they're based on mpsc and now we're having one process per machine instead of one thread. Maybe they should be removed?

### CODE REVIEW

**Comment by Ekleog** [comment]
Seems to me like the CI failure in if_watch is unrelated to this PR. I hopefully have fixed the lint with the latest push, but am not sure how to proceed with the if_watch CI failure.

**Comment by Ekleog** [comment]
Well actually looks like clippy also finds issues in parts of the code I haven't touched, so… guess the lint check won't be green either :sweat_smile:

**Review by rkuhn — APPROVED** [review]
Yes, this looks very good! Will investigate the CI failures (that has been on my todo list for too long) and then merge. Thanks!

(probably not today, though)

**Comment by Ekleog** [comment]
Great, thanks!

**Comment by rkuhn** [comment]
@Ekleog in case you missed it: I’ve been playing around a bit (and fixing CI a lot) in #32.

**Comment by rkuhn** [comment]
I merged this via the other PR since that one contains several useful fixes and improvements. We can continue honing this new `ipc` feature in a new PR, or I could cut a new release if your itch has successfully been scratched :-)

**Comment by Ekleog** [comment]
Thank you for all you did in the other PR!

I'm just a bit curious about something you said in the other PR: I don't see how checking that the function-exported unmangled symbol matches the requested name is any better from a type safety point of view than just using the function name that we know from the macro? As symbols don't contain any type information. (If we used the mangled symbol it might bring some typing improvements that said, but I'm not sure it'd be worth the stability limitations)

The one thing I see it brings is, that at `.spawn()` time it checks that the name being requested is indeed a symbol defined in the binary, be it a machine actually declared in `main` or not. As such, I'm not sure the benefit (having a panic instead of a compile error upon a typo in a machine name) is worth the additional infra required of end-users (no-mangle, pub, build.rs)?

However, what you did regarding type inference is great, and definitely more usable than what I did that required copying the types in the macro!

(FWIW, I tried writing macros to both have the advantage of "no spawning an unexisting machine" and "not relying on linker shenanigans", but it turns out to stay sane by the end of it I'd need proc-macros, and it'd probably be too big a thing to be worth it too — macro-defining macros is the place where I always ragequit since i did some once and they're still biting me)

**Comment by rkuhn** [comment]
Hehe, thanks for that final anecdote :-)

My intention was to remove the usage of string literals for binding things together: since we’re using exactly the same binary image to spawn the machines, we can rely on the fact that a symbol referenced in the test runner can be “serialised” by sending its name to the machine and looking it up — it will be the very same symbol, so it will have the same type. And since it is a properly typed `fn` the user cannot make mistakes regarding the channels involved, everything is constrained by the Rust type checker. The only inconvenience is the need for using `-rdynamic` and `#[no_mangle]` because otherwise it is impossible to add these symbols to the dynamic symbol table — an alternative but much more involved path is reading the static symbol table instead, by hand.

**Comment by Ekleog** [comment]
Oh I think I now see what you mean by more type safety: the `spawn` interface now guarantees that the function is being passed the correct type.

I think an alternative solution would be something like this:
```rust
#[netsim_embed::machine]
fn foo(ipc::Receiver<()>) {
    todo!()
}

// generates code like
struct foo;

impl Machine for foo {
    type Arg = ();
    fn id(&self) -> &'static u128 {
        42 // 128-bit random integer generated at proc macro expand time
    }
    fn call(&self, a: ipc::Receiver<Self::Arg>) {
        todo!() // the previous contents of foo()
    }
}
```

Then `dispatch_machines` would generate code like:
```rust
$(
    if arg == $m.id() {
        // call $m.call() with the proper ipc arguments like now
    }
)*
```

And `spawn` would look like:
```rust
fn spawn<M: Machine>(m: M) -> ipc::Sender<Self::Arg> {
    // execute self with argument m.id()
}
```

WDYT? The biggest drawback I see is that it requires a proc macro, but between this and requiring a build.rs and no_mangle, I'm thinking it'd still be better. Also, it'd actually bring more type safety, by virtue of the fact that the data exchanged over CLI argument would actually be "signed" by a random 128-bit value that changes at each build, so it'd be very hard for the user to pass the wrong type of ipc channel

**Comment by Ekleog** [comment]
Or we could make it into a non-proc-macro, but it's a bit more ugly to use:
```rust
netsim_embed::machine! {
    fn foo(a: ipc::Receiver<()>) {
        todo!()
    }
}
```

**Comment by rkuhn** [comment]
Yes, that would provide the same type checking coverage while getting rid of the `build.rs` requirement. I’d prefer the declarative macro due to better IDE support. The only downside I see is that `foo` is declared as `fn` in the program text but becomes a `struct` in the compiled program, which is somewhat confusing — luckily it should be rare for someone wanting to manually call the function. The trait’s associated functions should not have a `&self` argument: it wouldn’t be used anyway because it provides no value (literally :-) ).

**Comment by Ekleog** [comment]
You're right! I have them here because I originally wanted to use the `linkme` crate to remove the need for `declare_machines!`… but then I remembered that having a `type Arg` made `MachineFn` not object-safe, so that couldn't work.

So I've just submitted a PR with the proc macro that generates all the code, and also removed one layer of ipc-channel for the end-user of netsim-embed by hiding it into netsim-embed itself :) https://github.com/ipfs-rust/netsim-embed/pull/33

**Pull request merged**
